[package]
name = "jtop"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpu-monitor = "0.1.1"
psutil = "3.2.2"
terminal_size = "0.3.0"
